// Code generated by "stringer -type=Protocol"; DO NOT EDIT.

package termimg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unsupported-0]
	_ = x[ITerm2-1]
	_ = x[Kitty-2]
}

const _Protocol_name = "UnsupportedITerm2Kitty"

var _Protocol_index = [...]uint8{0, 11, 17, 22}

func (i Protocol) String() string {
	if i < 0 || i >= Protocol(len(_Protocol_index)-1) {
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[i]:_Protocol_index[i+1]]
}
